export default [
  {
    id: 1,
    title: "stream of thought in new age narratives",
    Image: "Blog-single-img6-417x292.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 2,
    title: "stream of thought in new age narratives",
    Image: "img1.jpg",
    date: "20 august 2020",
    type: "movies",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 3,
    title: "stream of thought in new age narratives",
    Image: "img2.jpg",
    date: "20 august 2020",
    type: "movies",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 4,
    title: "stream of thought in new age narratives",
    Image: "img3.jpg",
    date: "20 august 2020",
    type: "movies",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 5,
    title: "stream of thought in new age narratives",
    Image: "img4.jpg",
    date: "20 august 2020",
    type: "movies",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 6,
    title: "stream of thought in new age narratives",
    Image: "img5.jpg",
    date: "20 august 2020",
    type: "movies",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 7,
    title: "stream of thought in new age narratives",
    Image: "img6.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 8,
    title: "stream of thought in new age narratives",
    Image: "img7.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 9,
    title: "stream of thought in new age narratives",
    Image: "Blog-single-img6-417x292.jpg",
    date: "20 august 2020",
    type:'poem',
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 10,
    title: "stream of thought in new age narratives",
    Image: "img1.jpg",
    date: "20 august 2020",
    type: "visual art",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 11,
    title: "stream of thought in new age narratives",
    Image: "img2.jpg",
    date: "20 august 2020",
    type: "visual art",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 12,
    title: "stream of thought in new age narratives",
    Image: "img3.jpg",
    date: "20 august 2020",
    type: "visual art",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 13,
    title: "stream of thought in new age narratives",
    Image: "img4.jpg",
    date: "20 august 2020",
    type: "visual art",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 14,
    title: "stream of thought in new age narratives",
    Image: "img5.jpg",
    date: "20 august 2020",
    type: "visual art",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 15,
    title: "stream of thought in new age narratives",
    Image: "img6.jpg",
    date: "20 august 2020",
    type: "visual art",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 16,
    title: "stream of thought in new age narratives",
    Image: "img7.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 17,
    title: "stream of thought in new age narratives",
    Image: "Blog-single-img6-417x292.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 18,
    title: "stream of thought in new age narratives",
    Image: "img1.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 19,
    title: "stream of thought in new age narratives",
    Image: "img2.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 20,
    title: "stream of thought in new age narratives",
    Image: "img3.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 21,
    title: "stream of thought in new age narratives",
    Image: "img4.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 22,
    title: "stream of thought in new age narratives",
    Image: "img5.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 23,
    title: "stream of thought in new age narratives",
    Image: "img6.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 24,
    title: "stream of thought in new age narratives",
    Image: "img7.jpg",
    date: "20 august 2020",
    type: "books",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
];
