export default [
  {
    id: 1,
    title: "stream of thought in new age narratives",
    Image: "Blog-single-img6-417x292.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 2,
    title: "stream of thought in new age narratives",
    Image: "img1.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 3,
    title: "stream of thought in new age narratives",
    Image: "img2.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 4,
    title: "stream of thought in new age narratives",
    Image: "img3.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 5,
    title: "stream of thought in new age narratives",
    Image: "img4.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 6,
    title: "stream of thought in new age narratives",
    Image: "img5.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 7,
    title: "stream of thought in new age narratives",
    Image: "img6.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
  {
    id: 8,
    title: "stream of thought in new age narratives",
    Image: "img7.jpg",
    date: "20 august 2020",
    type: "poem",
    Comment: "1 comment",
    icon: "icon.jpg",
  },
];
